### PR TITLE
android-x86 download URL changed

### PR DESCRIPTION
**Pull request by aahutsal**

### CODE REVIEW

**Comment by aahutsal** [comment]
Changed ISO download URL (old one was broken)

**Comment by vdloo** [comment]
thanks!

**Comment by aahutsal** [comment]
There are still some issues with builder on my machine. Looks like some keystroke during `Run Android in Debug mode` is not sent (or being sent sooner) which cause build failure. Trying to find it locally. 
Could you put your eye on that too? Would be nice to make Android 8.1 branch as well (ISO download is available).

**Comment by vdloo** [comment]
Hi @gutsal-arsen, I'm currently not working on running GNU/Linux userland applications on Android anymore so I'm afraid I can't help you much with this since I haven't used this builder in a long time. But if I recall correctly the keystroke sending was pretty flaky and time-sensitive. Perhaps it would help if you increased the sleeps between each keystroke a bit and tried the run a couple of times? Because there is no feedback mechanism (it just sends blind keystrokes until it has a running Linux chroot with SSH and packer can run the provisioning script) sleeps that worked on my desktop back then might not work on your machine. You can try starting with longer delays to increase the chance of success.

**Comment by aahutsal** [comment]
Well, I'll debug it and try to find the issue. Will let you know.
Arsen A. Gutsal
SOFTSKY
<http://t.yesware.com/tt/c295780911eef2cf5954990615b4538cfd580e2a/64b3583a14737f52c063529fd9ea44d1/7b9f91b4a7d52b621d7141d44caf3489/www.softsky.com.ua>,
CTO
E: a.gutsal@softsky.com.ua
P: +380(96)599-63-28


пт, 16 лист. 2018 о 11:58 Rick van de Loo <notifications@github.com> пише:

**Pull request merged**
